
package be.cytomine.client.abst;

import be.cytomine.client.*;
import java.util.*;
import org.json.simple.*;

import java.util.List;
import org.json.simple.JSONObject;


/**
 * Response for sequence possibilities
 * 
 * @author ClientBuilder (Loïc Rollus)
 * @version 0.1
 * 
 * DO NOT EDIT THIS FILE. THIS IS CODE IS BUILD AUTOMATICALY. ALL CHANGE WILL BE LOST AFTER NEXT GENERATION.
 * 
 * IF YOU WANT TO EDIT A DOMAIN FILE (change method, add property,...), JUST EDIT THE CHILD FILE “YourDomain.java” instead of this file “AbstractYourDomain.java”. I WON'T BE CLEAR IF IT ALREADY EXIST.
 * 
 */
public abstract class AbstractSequencePossibilties
    extends AbstractDomain
{

    /**
     * Range of possible channel index for image group
     * 
     */
    protected List c;
    /**
     * Image channel index
     * 
     */
    protected List channel;
    /**
     * Image group id
     * 
     */
    protected List imageGroup;
    /**
     * Range of possible slice index for image group
     * 
     */
    protected List s;
    /**
     * Image slice index
     * 
     */
    protected List slice;
    /**
     * Range of possible time index for image group
     * 
     */
    protected List t;
    /**
     * Image time index
     * 
     */
    protected List time;
    /**
     * Range of possible zstack index for image group
     * 
     */
    protected List z;
    /**
     * Image zstack index
     * 
     */
    protected List zStack;

    public void build()
        throws Exception
    {
        

    
    }

    public void build(JSONObject json)
        throws Exception
    {
        
		this.c =JSONUtils.extractJSONList(json.get("c"));
		this.channel =JSONUtils.extractJSONList(json.get("channel"));
		this.imageGroup =JSONUtils.extractJSONList(json.get("imageGroup"));
		this.s =JSONUtils.extractJSONList(json.get("s"));
		this.slice =JSONUtils.extractJSONList(json.get("slice"));
		this.t =JSONUtils.extractJSONList(json.get("t"));
		this.time =JSONUtils.extractJSONList(json.get("time"));
		this.z =JSONUtils.extractJSONList(json.get("z"));
		this.zStack =JSONUtils.extractJSONList(json.get("zStack"));

    
    }

    public JSONObject toJSON()
        throws Exception
    {
        
		JSONObject json=new JSONObject();

		return json;
    
    }

}
